spring:
  application.name: TSM resell DB
  threads:
    virtual.enabled: true

  main:
    web-application-type: reactive
    profile:
      active: default

    #DB h2 connection
  datasource:
    driver-class-name: org.h2.Driver
    password:
    url: jdbc:h2:mem:tsmdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;
    username: sa
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: true
      hibernate:
        ddl-auto: update